# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HeavensWatch' do
	pod ‘Alamofire’
end

target 'HeavensWatchTests' do

end

target 'HeavensWatchUITests' do

end

target 'HeavensWatch WatchKit App' do

end

target 'HeavensWatch WatchKit Extension' do

end

